def hop(num)
  hop(num - 1) if num > 1
  puts 'hop! ' * num + 'One more time...'
end

hop(6)


# hop! One more time...
# hop! hop! One more time...
# hop! hop! hop! One more time...
# hop! hop! hop! hop! One more time...
# hop! hop! hop! hop! hop! One more time...
# hop! hop! hop! hop! hop! hop! One more time...
